---
namespace: szaffarano
name: general
version: 1.2.2
readme: README.md
authors:
  - Sebastian Zaffarano <sebas@zaffarano.com.ar>
description: Set of Ansible roles and playbooks for general purpose usage.
license:
  - MIT
tags:
  - bootstrap
  - raspberry
  - k3s
  - general
  - networking
  - vpn
dependencies:
  "ansible.posix": ">=1.3.0,<1.4.0"
  "community.general": ">=4.6.0,<4.7.0"
repository: https://github.com/szaffarano/szaffarano.general
documentation: https://github.com/szaffarano/szaffarano.general
homepage: https://github.com/szaffarano/szaffarano.general
issues: https://github.com/szaffarano/szaffarano.general/issues
build_ignore: []
