{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN apt-get update && apt-get install -y \
  systemd-sysv python3 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# vim: ft=dockerfile
